server:
  port: 8080
---
spring:
  application:
    name: api-gateway
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**, /auth/**
          filters:
            - JWTFilter
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**, /category/**
          filters:
            - JWTFilter
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/cart/**, /order/**
          filters:
            - JWTFilter
      httpclient:
        connect-timeout: 1000
        response-timeout: 5000