server:
  port: 8080
---
spring:
  application:
    name: api-gateway
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
spring:
  cloud:
    gateway:
      routes:
        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/user/**, /auth/**