server:
  port: 8085
---
spring:
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    queue: user-service
    exchange: rabbitmq.exchange
    routingkey: user-service
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: khang.dacntt2@gmail.com
    password: afiqemoiyxzgthxg
    port: 587