server:
  port: 8085
---
spring:
  application:
    name: mail-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: khang.dacntt2@gmail.com
    password: afiqemoiyxzgthxg
    port: 587
rabbitmq:
  queue: user-service
  exchange: rabbitmq.exchange
  routingkey: user-service
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka