server:
  port: 8085
---
spring:
  application:
    name: mail-service
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: <your account>
    password: <your password>
    port: 587
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: mailQueue
          group: mailConsumerGroup
      rabbit:
        bindings:
          input:
            consumer:
              exchangeType: topic
              bindingRoutingKey: mailQueue
              exchangeName: rabbitmq.exchange
#rabbitmq:
#  queue: user-service
#  exchange: rabbitmq.exchange
#  routingkey: user-service
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
