server:
  port: 8081
---
spring:
  application:
    name: user-service
---
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/user_service'
    username: 'postgres'
    password: '123456'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
---
jwt:
  secretKey: 'YvWrvQ198TtPYQNBs6VyWJRdgtAVjQMq'
  expirationMs: '604800000' # Expired in 7 days
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher