server:
  port: 8081
---
spring:
  application:
    name: user-service
  datasource:
    url: 'jdbc:postgresql://localhost:5432/user_service'
    username: 'postgres'
    password: '123456'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output:
          destination: mailQueue
          group: mailConsumerGroup
      rabbit:
        bindings:
          output:
            producer:
              exchangeType: topic
              bindingRoutingKey: mailQueue
              exchangeName: rabbitmq.exchange
---
jwt:
  secretKey: 'YvWrvQ198TtPYQNBs6VyWJRdgtAVjQMq'
  expirationMs: '604800000' # Expired in 7 days
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
feign:
  client:
    config:
      default:
        loggerLevel: BASIC
        fallback: com.internproject.userservice.fallback.UserServiceFallback
      IUserService:
        loggerLevel: FULL
  circuitbreaker:
    enabled: true
---
logging:
  level:
    com.internproject.userservice.service: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE