server:
  port: 8083
---
spring:
  application:
    name: order-service
---
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/order_service'
    username: 'postgres'
    password: '123456'
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: update
---
app:
  jwtSecret: 'YvWrvQ198TtPYQNBs6VyWJRdgtAVjQMq'
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
---
logging:
  level:
    com.internproject.orderservice.service: DEBUG
feign:
  client:
    config:
      default:
        loggerLevel: BASIC
      IProductService:
        loggerLevel: FULL