server:
  port: 8082
---
spring:
  application:
    name: product-service
---
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/product_service'
    username: 'postgres'
    password: '123456'
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: update
---
app:
  jwtSecret: 'YvWrvQ198TtPYQNBs6VyWJRdgtAVjQMq'
  jwtExpirationMs: '604800000' # Expired in 7 days
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher