server:
  port: 8082
---
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: 'jdbc:postgresql://localhost:5432/product_service'
    username: 'postgres'
    password: '123456'
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: none
  application:
    name: product-service
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
---
app:
  jwtSecret: 'YvWrvQ198TtPYQNBs6VyWJRdgtAVjQMq'
  jwtExpirationMs: '604800000' # Expired in 7 days
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
logging:
  level:
    com.internproject.productservice.service: DEBUG
feign:
  client:
    config:
      default:
        loggerLevel: BASIC
        fallback: com.internproject.productservice.fallback.UserServiceFallback
      IUserService:
        loggerLevel: FULL
  circuitbreaker:
    enabled: true